### ISSUE TITLE
从安全角度考虑，尽量避免直接使用root登录数据库

### ISSUE THREAD

**Issue by Senorsen** [InsZVA/QSC#2]
权限应尽量隔离，保证各应用权限最小分配原则。

**Comment by Senorsen** [comment]
https://github.com/InsZVA/QSC/blob/master/index.php#L49

**Comment by zenozeng** [comment]
以及配置文件最好还是分离比较好

**Comment by Armour** [comment]
话说看到明文密码感觉很。。。 突然在想那个密码会不会是你某些账户的密码嘤嘤嘤
